var annotated_dup =
[
    [ "AxeProjectile", "class_axe_projectile.html", "class_axe_projectile" ],
    [ "Enemy", "class_enemy.html", "class_enemy" ],
    [ "Enemybleed", "class_enemybleed.html", "class_enemybleed" ],
    [ "EnemySpawner", "class_enemy_spawner.html", "class_enemy_spawner" ],
    [ "EnemyStats", "class_enemy_stats.html", "class_enemy_stats" ],
    [ "FireWand", "class_fire_wand.html", "class_fire_wand" ],
    [ "Game", "class_game.html", null ],
    [ "Garlic", "class_garlic.html", "class_garlic" ],
    [ "GarlicAura", "class_garlic_aura.html", "class_garlic_aura" ],
    [ "KillManager", "class_kill_manager.html", "class_kill_manager" ],
    [ "KillsButton", "class_kills_button.html", "class_kills_button" ],
    [ "KillsUI", "class_kills_u_i.html", "class_kills_u_i" ],
    [ "LevelUpUI", "class_level_up_u_i.html", "class_level_up_u_i" ],
    [ "Lightning", "class_lightning.html", "class_lightning" ],
    [ "LightningBeam", "class_lightning_beam.html", "class_lightning_beam" ],
    [ "LightningChain", "class_lightning_chain.html", "class_lightning_chain" ],
    [ "MagicMissile", "class_magic_missile.html", "class_magic_missile" ],
    [ "MagicMissileProjectile", "class_magic_missile_projectile.html", "class_magic_missile_projectile" ],
    [ "Magnet", "class_magnet.html", "class_magnet" ],
    [ "MobEntry", "class_mob_entry.html", "class_mob_entry" ],
    [ "PassiveData", "class_passive_data.html", "class_passive_data" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PowerUpButton", "class_power_up_button.html", "class_power_up_button" ],
    [ "Projectile", "class_projectile.html", "class_projectile" ],
    [ "StartButton", "class_start_button.html", "class_start_button" ],
    [ "StartButtonHover", "class_start_button_hover.html", "class_start_button_hover" ],
    [ "UpgradeData", "class_upgrade_data.html", "class_upgrade_data" ],
    [ "WaveDefinition", "class_wave_definition.html", "class_wave_definition" ],
    [ "Weapon", "class_weapon.html", "class_weapon" ],
    [ "WeaponStats", "class_weapon_stats.html", "class_weapon_stats" ],
    [ "XpOrb", "class_xp_orb.html", "class_xp_orb" ]
];